### ISSUE TITLE
Ruby error when running the kofam workflow

### ISSUE THREAD

**Issue by ParkvilleData** [takaram/kofam_scan#16]
I'm using the eukaryotes profile (profiles/eukaryote.hal)

and all the programs are in my path.

Thanks for your help!

```
[bobbieshaban@spartan-bm067 kofam]$ ./exec_annotation -o result.txt R5300_S1.prodigal.proteins.fa --cpu=10
Traceback (most recent call last):
        6: from .../exec_annotation:7:in `<main>'
        5: from ../kofam/lib/kofam_scan/cli.rb:16:in `run'
        4: from .../kofam/lib/kofam_scan/config.rb:11:in `load'
        3: from .../psych.rb:349:in `safe_load'
        2: from .../psych.rb:390:in `parse'
        1: from ..../psych.rb:456:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 4 column 1 (Psych::SyntaxError)
```

**Comment by YANWF2020** [comment]
@ParkvilleData hello， may i ask whether you solved this problem? I encountered the same problem, and could you share your solution? thank you so much!

**Comment by wanxn518** [comment]
@ParkvilleData I also encountered this problem.
```
/public/home/wanxn/miniconda3/envs/kofam/lib/ruby/3.1.0/psych.rb:455:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 5 column 1 (Psych::SyntaxError)
        from /public/home/wanxn/miniconda3/envs/kofam/lib/ruby/3.1.0/psych.rb:455:in `parse_stream'
        from /public/home/wanxn/miniconda3/envs/kofam/lib/ruby/3.1.0/psych.rb:399:in `parse'
        from /public/home/wanxn/miniconda3/envs/kofam/lib/ruby/3.1.0/psych.rb:324:in `safe_load'
        from /public/home/wanxn/apps/KofamKOALA/bin/kofam_scan-1.3.0/lib/kofam_scan/config.rb:11:in `load'
        from /public/home/wanxn/apps/KofamKOALA/bin/kofam_scan-1.3.0/lib/kofam_scan/cli.rb:16:in `run'
        from ../exec_annotation:7:in `<main>'
```
