### ISSUE TITLE
undefined method `end_with?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by lijing28101** [takaram/kofam_scan#17]
I'm trying to run kofam_scan with ruby 2.6.6, and I got the error as below:

```
Traceback (most recent call last):
        5: from ./exec_annotation:7:in `<main>'
        4: from /work/LAS/mash-lab/jing/bin/kofam_scan/lib/kofam_scan/cli.rb:21:in `run'
        3: from /work/LAS/mash-lab/jing/bin/kofam_scan/lib/kofam_scan/executor.rb:8:in `execute'
        2: from /work/LAS/mash-lab/jing/bin/kofam_scan/lib/kofam_scan/executor.rb:35:in `execute'
        1: from /work/LAS/mash-lab/jing/bin/kofam_scan/lib/kofam_scan/executor.rb:104:in `run_hmmsearch'
/work/LAS/mash-lab/jing/bin/kofam_scan/lib/kofam_scan/executor.rb:152:in `lookup_profiles': undefined method `end_with?' for nil:NilClass (NoMethodError)
```

**Comment by sashulkaSh** [comment]
the same error...

**Comment by sashulkaSh** [comment]
with ruby 2.4.5p335

**Comment by merytouceda** [comment]
I have the same error. 

I have followed this tutorial: https://taylorreiter.github.io/2019-05-11-kofamscan/ 
Except for the download of kofamscan "wget ftp://ftp.genome.jp/pub/tools/kofamscan/kofamscan.tar.gz", which didn't work and I cloned this repo instead. 

My conda environment looks like this: 
```
# packages in environment 
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
gdbm                      1.18                 h0a1914f_2    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
hmmer                     3.3.2                h87f3376_2    bioconda
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.7                h0b41bf4_2    conda-forge
parallel                  20170422             pl5.22.0_0    bioconda
perl                      5.22.0.1                      0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
ruby                      3.1.2                hc054e64_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
```

Has anyone encountered this issue and been able to solve it?
