### ISSUE TITLE
parallel.rb:28:in `write': Broken pipe (Errno::EPIPE)

### ISSUE THREAD

**Issue by jowodo** [takaram/kofam_scan#27]
Hi, 

I'm on a HPC system. That means users don't have write permissions to the kofam folder. 
When I execute the following: 
```
./exec_annotation -o result -p $profile -k $ko $FA
```
I get 
```
Ignoring etc-1.2.0 because its extensions are not built. Try: gem pristine etc --version 1.2.0
Traceback (most recent call last):
        10: from ./exec_annotation:7:in `<main>'
         9: from /scratch/students/apptest/2022-09-23-kofam/kofambin/lib/kofam_scan/cli.rb:21:in `run'
         8: from /scratch/students/apptest/2022-09-23-kofam/kofambin/lib/kofam_scan/executor.rb:8:in `execute'
         7: from /scratch/students/apptest/2022-09-23-kofam/kofambin/lib/kofam_scan/executor.rb:35:in `execute'
         6: from /scratch/students/apptest/2022-09-23-kofam/kofambin/lib/kofam_scan/executor.rb:107:in `run_hmmsearch'
         5: from /scratch/students/apptest/2022-09-23-kofam/kofambin/lib/kofam_scan/parallel.rb:27:in `exec'
         4: from /home/apps/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/open3-0.1.1/lib/open3.rb:102:in `popen3'
         3: from /home/apps/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/open3-0.1.1/lib/open3.rb:227:in `popen_run'
         2: from /scratch/students/apptest/2022-09-23-kofam/kofambin/lib/kofam_scan/parallel.rb:28:in `block in exec'
         1: from /scratch/students/apptest/2022-09-23-kofam/kofambin/lib/kofam_scan/parallel.rb:28:in `puts'
/scratch/students/apptest/2022-09-23-kofam/kofambin/lib/kofam_scan/parallel.rb:28:in `write': Broken pipe (Errno::EPIPE)
```

any idea or hint in the right direction would be appreciated. 

Best regards

**Comment by jowodo** [comment]
The problem was that parallel was not loaded/ installed. 
See #7
