### ISSUE TITLE
Issue when I run the analysis

### ISSUE THREAD

**Issue by queirozhanna** [takaram/kofam_scan#34]
Hello, 

I've tried the command the tutorial suggests
`$ ./exec_annotation -o output.tsv input.fasta` but I when I run it on my terminal, I get the message "Error: KO list not given"

I've also tried this command:

`$ ./exec_annotation -p /path/to/profiles/directory -k /path/to/ko_list/directory -o output.tsv input.fasta --cpu=8` 

but I get this message

`/home/hanna/kofamscan/bin/kofam_scan-1.3.0/lib/kofam_scan/ko.rb:11:in `gets': Is a directory @ io_fillbuf - fd:5 /home/hanna/kofamscan/db/ (Errno::EISDIR)
        from /home/hanna/kofamscan/bin/kofam_scan-1.3.0/lib/kofam_scan/ko.rb:11:in `parse'
        from /home/hanna/kofamscan/bin/kofam_scan-1.3.0/lib/kofam_scan/executor.rb:80:in `block in parse_ko'
        from /home/hanna/kofamscan/bin/kofam_scan-1.3.0/lib/kofam_scan/executor.rb:80:in `open'
        from /home/hanna/kofamscan/bin/kofam_scan-1.3.0/lib/kofam_scan/executor.rb:80:in `parse_ko'
        from /home/hanna/kofamscan/bin/kofam_scan-1.3.0/lib/kofam_scan/executor.rb:22:in `execute'
        from /home/hanna/kofamscan/bin/kofam_scan-1.3.0/lib/kofam_scan/executor.rb:8:in `execute'
        from /home/hanna/kofamscan/bin/kofam_scan-1.3.0/lib/kofam_scan/cli.rb:21:in `run'
        from ./exec_annotation:7:in `<main>'`

I've searched for a way to solve this issue but none of the solutions worked. 😣

**Comment by bheimbu** [comment]
Hi @queirozhanna,

did you 

> Download KOfam database from ftp://ftp.genome.jp/pub/db/kofam/ and decompress it. You will get profile HMMs in profiles/ directory and ko_list.

If so specify the path with 
```
exec_annotation -o output.tsv input.fasta -p /path/to/your/profiles/directory/ -k /path/to/your/ko_list
```

Cheers Bastian

**Comment by queirozhanna** [comment]
thank you a lot! @bheimbu
