### ISSUE TITLE
wrong number of arguments

### ISSUE THREAD

**Issue by WJT0925** [takaram/kofam_scan#35]
~/software/KOALA/kofam_scan-1.3.0/bin/exec_annotation -o ./kofam.out -p ~/software/KOALA/kofam_scan-1.3.0/db/profiles -k ~/software/KOALA/kofam_scan-1.3.0/db/profiles/eukaryote.hal --cpu 5 --tmp-dir ./tmp -E 1e-5 -f detail-tsv Pshi.short.pep 
Traceback (most recent call last):
	11: from /home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/exec_annotation:7:in `<main>'
	10: from /home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/lib/kofam_scan/cli.rb:21:in `run'
	 9: from /home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/lib/kofam_scan/executor.rb:8:in `execute'
	 8: from /home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/lib/kofam_scan/executor.rb:22:in `execute'
	 7: from /home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/lib/kofam_scan/executor.rb:80:in `parse_ko'
	 6: from /home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/lib/kofam_scan/executor.rb:80:in `open'
	 5: from /home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/lib/kofam_scan/executor.rb:80:in `block in parse_ko'
	 4: from /home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/lib/kofam_scan/ko.rb:12:in `parse'
	 3: from /home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/lib/kofam_scan/ko.rb:12:in `each_line'
	 2: from /home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/lib/kofam_scan/ko.rb:15:in `block in parse'
	 1: from /home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/lib/kofam_scan/ko.rb:15:in `new'
/home/jingtian/software/KOALA/kofam_scan-1.3.0/bin/lib/kofam_scan/ko.rb:35:in `initialize': wrong number of arguments (given 1, expected 12) (ArgumentError)

**Comment by faye92sun** [comment]
I'm having the same problem, hoping for a solution.
