### ISSUE TITLE
config.rb:26:in `initialize': undefined method `map' for "profile:profiles":String (NoMethodError)        }.merge(initial_values.map { |k, v| [k.intern, v] }.to_h)   Did you mean?  tap

### ISSUE THREAD

**Issue by 11916090** [takaram/kofam_scan#38]
Hi,
   i set and download kofam_scan-1.3.0 as follow steps:
conda create -n kofamscan
conda activate kofamscan
conda install -c conda-forge ruby
conda install -c bioconda hmmer
conda install -c conda-forge parallel

mkdir KofamKOALA && cd KofamKOALA
wget https://www.genome.jp/ftp/db/kofam/ko_list.gz
wget https://www.genome.jp/ftp/db/kofam/profiles.tar.gz
gunzip ko_list.gz
tar -xzvf profiles.tar.gz

but when i run  "exec_annotation -o Dlongan.querryko --cpu 2 --format mapper -E 1e-5 d.pep.fasta " report an error as follws:
 config.rb:26:in `initialize': undefined method `map' for "/path/profiles":String (NoMethodError)
      }.merge(initial_values.map { |k, v| [k.intern, v] }.to_h)
                            ^^^^
Did you mean?  tap

I have no idea how to slove this problem, can you give me some help, thanks.

wen

**Comment by Betula0422** [comment]
Hi there, I have encountered the same problem with you. Have you solved the problem?
